### ISSUE TITLE
More coverage tests needed

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/raet#48]
This is a brief description of the test cases that have to be covered by nose tests.
1. Verify that joiner.accept is idempotent.
   since joinent.accept is retried and joiner.accept is not locked out of duplicates.
   Ie send duplicate accept packets
   because ack was dropped.
2. Verify that joinent.join is idempotent?. Ie send duplicate join packets because accept was dropped.
3. Test Joiner.process where  key status changes during transaction. Typically from pended to accept or rejected.
   But also from accepted to rejected while a joiner is in process so that can dynamically disavow a remote
4. Test for Stalent
   Test for stale sid checking and renewal for roadstack
5. Tests to verify reap and restore of dead remotes. No real reaping unit tests yet.
   Test reapTimer
6. Test for clean option that overrides Road persistence upon stack creation.
7. Verify that minion quits if it rejects the master keys  on its join. That is
   if it cannot join to any master it quits.

**Comment by thatch45** [comment]
Done
