### ISSUE TITLE
Python2 compatibility?

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/raet#54]
Some of the imported packages used are python3 only, such as importlib or enum. Which python versions does the RAET transport target? Arch installs salt-raet by default using python2 and starting the master fails because salt currently requires python2 and it chokes on the python3 modules.

I'd love to write some PRs for version compatibility, just wanted to know the intended deployment strategy.

**Comment by SmithSamuelM** [comment]
importlib and enum have back ported packages that run in python2.

**Comment by aneeshusa** [comment]
Sweet, I didn't know that! In that case, this would be a packaging problem with Arch: the salt-raet package should have a dependency on python2-enum34. (python2 is python2.7 on Arch so no need for an importlib dependency.)

**Comment by techhat** [comment]
Ping @gtmanfred.

**Comment by gtmanfred** [comment]
Please open a bug on bugs.archlinux.org on the community project and I will try and get to it later today.

**Comment by aneeshusa** [comment]
Great, left a [bug report](https://bugs.archlinux.org/task/44225) on the tracker.

**Comment by gtmanfred** [comment]
should be fixed now in 0.6.3-1 release I am pushing in a minute. Yall should close this.
