### ISSUE TITLE
Can RAET be used as a message bus/transport?

### ISSUE THREAD

**Issue by stephanbuys** [saltstack/raet#64]
Hi,

I've been scanning for a reliable _and_ secure way to transport event messages from generating systems to a central log management host (a syslog replacement for lack of a better description). Do you think RAET to fit such a purpose, is it fast? Some use cases could be in excess of 10,000 events per second.

Regards,
Stephan

**Comment by thatch45** [comment]
yes, raet could be used for this

**Comment by AdrienPensart** [comment]
Do someone has smalls example to use it without salt ? (with respect that it was only built with salt in mind), like simple patterns ?

**Comment by thatch45** [comment]
The only other project I know if that is making heavy use of RAET is Plenum:
https://github.com/evernym/plenum
This project might have some cleaner code examples, but I must admit I have not looked too closely

**Comment by SmithSamuelM** [comment]
The unit test for raet have some good examples
see raet/raet/road/test/test_stacking.py  

class BasicTestCase(unittest.TestCase):
    """"""

    def setUp(self):
        self.store = Store(stamp=0.0)
        self.timer = StoreTimer(store=self.store, duration=1.0)

        self.baseDirpath=tempfile.mkdtemp(prefix="raet",  suffix="base", dir=TEMPDIR)
        stacking.RoadStack.Bk = raeting.BodyKind.json.value

        #main stack
        mainName = "main"
        mainDirpath = os.path.join(self.baseDirpath, 'road', 'keep', mainName)
        signer = nacling.Signer()
        mainSignKeyHex = signer.keyhex
        privateer = nacling.Privateer()
        mainPriKeyHex = privateer.keyhex


        #other stack
        otherName = "other"
        otherDirpath = os.path.join(self.baseDirpath, 'road', 'keep', otherName)
        signer = nacling.Signer()
        otherSignKeyHex = signer.keyhex
        privateer = nacling.Privateer()
        otherPriKeyHex = privateer.keyhex


        keeping.clearAllKeep(mainDirpath)
        keeping.clearAllKeep(otherDirpath)

        self.main = stacking.RoadStack(store=self.store,
                                       name=mainName,
                                       main=True,
                                       auto=raeting.AutoMode.once.value,
                                       sigkey=mainSignKeyHex,
                                       prikey=mainPriKeyHex,
                                       dirpath=mainDirpath,
                                       )

        self.other = stacking.RoadStack(store=self.store,
                                        name=otherName,
                                        auto=raeting.AutoMode.once.value,
                                        ha=("", raeting.RAET_TEST_PORT),
                                        sigkey=otherSignKeyHex,
                                        prikey=otherPriKeyHex,
                                        dirpath=otherDirpath,
                                        )

**Comment by SmithSamuelM** [comment]
def join(self, timeout=None):
        '''
        Utility method to do join. Call from test method.
        '''
        console.terse("\nJoin Transaction **************\n")
        if not self.other.remotes:
            self.other.addRemote(estating.RemoteEstate(stack=self.other,
                                                       #name=self.main.local.name,
                                                       fuid=0, # vacuous join
                                                       sid=0, # always 0 for join
                                                       ha=self.main.local.ha)
                                )
        self.other.join(timeout=timeout)
        self.service()

**Comment by SmithSamuelM** [comment]
I forgot, there is a raet tutorial in
/Data/Code/public/raet/docs/topics/tutorial.rst
/Data/Code/public/raet/docs/topics/examples_road.py

**Comment by SmithSamuelM** [comment]
This should be enough to get you started.

**Comment by AdrienPensart** [comment]
Thank you !
