### ISSUE TITLE
raet fails to import: @enum.unique

### ISSUE THREAD

**Issue by ahammond** [saltstack/raet#66]
I've attempted to package raet 0.6.3, however I'm getting the following error on import. Help?

```
[vagrant@prd-vm-uhs-62 ~]$ python
Python 2.6.6 (r266:84292, Dec  7 2011, 20:48:22) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import raet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/lib/python2.6/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.6/site-packages/raet/raeting.py", line 140, in <module>
    @enum.unique
AttributeError: 'module' object has no attribute 'unique'
>>> import enum
>>> enum
<module 'enum' from '/usr/lib/python2.6/site-packages/enum.py'>
>>> enum.__version__
'0.4.4'
```

**Comment by ahammond** [comment]
Using https://pypi.python.org/packages/source/r/raet/raet-0.6.3.tar.gz#md5=33bd888d71781fe97310656f473bc544

**Comment by cachedout** [comment]
@dmurphy18 Could you help out here?

**Comment by joehealy** [comment]
Given you are using python2.6, I guess you will need to have enum34 [1] or similar as a dependency.

[1] https://pypi.python.org/pypi/enum34

**Comment by ahammond** [comment]
I'll give it a shot. Thanks!

**Comment by ahammond** [comment]
That fixed it. I also had to install a library called six. Is there a requirements.txt for this anywhere?

**Comment by dmurphy18** [comment]
There is a 'raet-requirements.txt' file which contains libnacl and ioflo apart from raet.

The library six is to allow for moving to support strings properly in python 3.

I shall look at adding enum34 and six to the raet-requirements file

**Comment by s0undt3ch** [comment]
Six and enum34 are pulled in when pip installing ioflo or at least, they were previously being pulled...
